apiVersion: run.tanzu.vmware.com/v1alpha1               #TKG API endpoint
kind: TanzuKubernetesCluster                            #required parameter
metadata:
  name: toobig                                          #clustuer name, user defined
  namespace: fci                                        #supervisor namespace
spec:
  distribution:
    version: v1.18                                      #resolved kubernetes version
  topology:
    controlPlane:
      count: 3                                          #number of control plane nodes
      class: guaranteed-large                          #vmclass for control plane nodes
      storageClass: pacific-gold-storage-policy         #storageclass for control plane
    workers:
      count: 8                                          #number of worker nodes
      class: guaranteed-large                          #vmclass for worker nodes
      storageClass: pacific-gold-storage-policy         #storageclass for worker nodes
