apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: llange@vmware.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: proveofwork 
          #hostedZoneName: 'sademo.de.'
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: key.json
